---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: '1.0.3'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: gotk-system
      interval: 1m
