---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: gotk-system
spec:
  dependsOn:
  - name: cert-manager
  interval: 5m0s
  path: ./manifests/prd/cert-manager-issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: gotk-system

