---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns
  namespace: gotk-system
spec:
  interval: 5m0s
  path: ./apps/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: gotk-system

