---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik
  namespace: gotk-system
spec:
  interval: 30m
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: gotk-system
spec:
  interval: 1m
  targetNamespace: traefik
  chart:
    spec:
      chart: traefik
      version: 9.6.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: gotk-system
  values:
    ingressClass:
      isDefaultClass: true
