apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

bases:
- github.com/kubernetes-sigs/external-dns//kustomize?ref=v0.7.4

resources:
- ./namespace.yaml

patchesStrategicMerge:
- ./deployment-flags.yaml
